### ISSUE TITLE
Error compiling using Arduino IDE 1.8.12

### ISSUE THREAD

**Issue by edumeneses** [mathiasbredholt/libmapper_arduino#5]
Library fails to compile using Arduino 1.8.12 (works fine with 1.8.10 though)

OBS: I'm using [libmapper v0.1.3](https://github.com/mathiasbredholt/libmapper_arduino/releases), even though the output claims 0.1.0 ...

Using the [Example_ESP32](https://github.com/mathiasbredholt/libmapper_arduino/tree/master/examples/Example_ESP32).

Error:
```
Arduino: 1.8.12 (Mac OS X), Board: "LOLIN D32 PRO, Enabled, Default, 80MHz, 115200, None"

sketch/Example_ESP32.ino.cpp.o:(.literal._Z20input_signal_handlerPvyPKviP10lo_timetag+0x4): undefined reference to `mapper_signal_length'
sketch/Example_ESP32.ino.cpp.o:(.literal._Z5setupv+0x34): undefined reference to `mapper_device_new'
sketch/Example_ESP32.ino.cpp.o:(.literal._Z5setupv+0x38): undefined reference to `mapper_device_add_output_signal'
sketch/Example_ESP32.ino.cpp.o:(.literal._Z5setupv+0x3c): undefined reference to `mapper_device_add_input_signal'
sketch/Example_ESP32.ino.cpp.o:(.literal._Z4loopv+0x8): undefined reference to `mapper_device_poll'
Multiple libraries were found for "WiFi.h"
sketch/Example_ESP32.ino.cpp.o:(.literal._Z4loopv+0xc): undefined reference to `mapper_signal_update_float'
 Used: /Users/edu/Library/Arduino15/packages/esp32/hardware/esp32/1.0.4/libraries/WiFi
 Not used: /Applications/Arduino.app/Contents/Java/libraries/WiFi
sketch/Example_ESP32.ino.cpp.o: In function `input_signal_handler(void*, unsigned long long, void const*, int, lo_timetag*)':
/Users/edu/Documents/Arduino/libraries/libmapper/examples/Example_ESP32/Example_ESP32.ino:43: undefined reference to `mapper_signal_length'
sketch/Example_ESP32.ino.cpp.o: In function `setup()':
/Users/edu/Documents/Arduino/libraries/libmapper/examples/Example_ESP32/Example_ESP32.ino:27: undefined reference to `mapper_device_new'
/Users/edu/Documents/Arduino/libraries/libmapper/examples/Example_ESP32/Example_ESP32.ino:30: undefined reference to `mapper_device_add_output_signal'
/Users/edu/Documents/Arduino/libraries/libmapper/examples/Example_ESP32/Example_ESP32.ino:31: undefined reference to `mapper_device_add_input_signal'
sketch/Example_ESP32.ino.cpp.o: In function `loop()':
/Users/edu/Documents/Arduino/libraries/libmapper/examples/Example_ESP32/Example_ESP32.ino:35: undefined reference to `mapper_device_poll'
/Users/edu/Documents/Arduino/libraries/libmapper/examples/Example_ESP32/Example_ESP32.ino:37: undefined reference to `mapper_signal_update_float'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board LOLIN D32 PRO.
```

**Comment by badebold** [comment]
Thanks! I've been using 1.8.10, I will try to locate the error asap!

**Comment by ChristianFrisson** [comment]
Works for me with Arduino 1.8.12 at commit 8cf3289c11ae239f2f5602c2dcc898e99e6e2d02 but on Ubuntu/Pop!_OS 20.04.

**Comment by badebold** [comment]
@ChristianFrisson Interesting, I will check again and see if I can replicate the issue one more time.

**Comment by edumeneses** [comment]
Does not work for me at VSC/PlatformIO as well (macOS Catalina 10.15.7, VSC 1.51.0, PlatformIO Core 5.0.2). Tried to compile the [Example_ESP32](https://github.com/mathiasbredholt/libmapper-arduino/blob/master/examples/Example_ESP32/Example_ESP32.ino) and got the output:

```debug
> Executing task: platformio run <

Processing tinypico (platform: espressif32; board: tinypico; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/tinypico.html
PLATFORM: Espressif 32 (2.0.0) > TinyPICO
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 3.10004.201016 (1.0.4) 
 - tool-esptoolpy 1.20600.0 (2.6.0) 
 - toolchain-xtensa32 2.50200.80 (5.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 27 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <WiFi> 1.0
|-- <libmapper> 0.1.5
Building in release mode
Compiling .pio/build/tinypico/src/main.cpp.o
Linking .pio/build/tinypico/firmware.elf
.pio/build/tinypico/src/main.cpp.o:(.literal._Z20input_signal_handlerPvyPKviP10lo_timetag+0x4): undefined reference to `mapper_signal_length'
.pio/build/tinypico/src/main.cpp.o:(.literal._Z5setupv+0x34): undefined reference to `mapper_device_new'
.pio/build/tinypico/src/main.cpp.o:(.literal._Z5setupv+0x38): undefined reference to `mapper_device_add_output_signal'
.pio/build/tinypico/src/main.cpp.o:(.literal._Z5setupv+0x3c): undefined reference to `mapper_device_add_input_signal'
.pio/build/tinypico/src/main.cpp.o:(.literal._Z4loopv+0x8): undefined reference to `mapper_device_poll'
.pio/build/tinypico/src/main.cpp.o:(.literal._Z4loopv+0xc): undefined reference to `mapper_signal_update_float'
.pio/build/tinypico/src/main.cpp.o: In function `input_signal_handler(void*, unsigned long long, void const*, int, lo_timetag*)':
/Users/edu/Documents/PlatformIO/Projects/Libmapper - ESP32/src/main.cpp:48: undefined reference to `mapper_signal_length'
.pio/build/tinypico/src/main.cpp.o: In function `setup()':
/Users/edu/Documents/PlatformIO/Projects/Libmapper - ESP32/src/main.cpp:31: undefined reference to `mapper_device_new'
/Users/edu/Documents/PlatformIO/Projects/Libmapper - ESP32/src/main.cpp:34: undefined reference to `mapper_device_add_output_signal'
/Users/edu/Documents/PlatformIO/Projects/Libmapper - ESP32/src/main.cpp:35: undefined reference to `mapper_device_add_input_signal'
.pio/build/tinypico/src/main.cpp.o: In function `loop()':
/Users/edu/Documents/PlatformIO/Projects/Libmapper - ESP32/src/main.cpp:35: undefined reference to `mapper_device_poll'
/Users/edu/Documents/PlatformIO/Projects/Libmapper - ESP32/src/main.cpp:41: undefined reference to `mapper_signal_update_float'
collect2: error: ld returned 1 exit status
*** [.pio/build/tinypico/firmware.elf] Error 1
============================================================================= [FAILED] Took 4.40 seconds =============================================================================
The terminal process "platformio 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

The only modifications I've made was to change the file extension to `.cpp` and add `#include <Arduino.h>` at the beginning of the file.

**Comment by badebold** [comment]
@edumeneses the error you're getting is a linker error, it means that the statically compiled library is not linked to the .elf file by platformio. I would argue that this is a separate issue, as it seems from this forum post that platformio does not support precompiled Arduino libraries.
https://community.platformio.org/t/using-a-precompiled-library-a/3405

You should be able to compile the example by adding
```
-L /path-to-libmappe-library/src/esp32 -lmapper
```
to the build_flags entry of your platformio config file.

**Comment by badebold** [comment]
I updated the library such that it contains all the source files of libmapper, liblo, zlib, and compat-idf. This is not the most elegant solution but it solves the problem with precompiled libraries for both Arduino IDE and platform.io. I will work on a system for automatically generating the library when libmapper is updated. Also, this change makes it possible to add libmapper-arduino to the Arduino library manager.

**Comment by badebold** [comment]
Commit 32a9ef26f0b609581f1ceba13fc2f58bd6515cf9 fixes this issue.

**Comment by edumeneses** [comment]
Thanks @mathiasbredholt! Just a note for future reference: I could not test/reproduce the Arduino 1.8.12 error in another machine.

**Comment by badebold** [comment]
@edumeneses You're welcome. I have been unable to compile libmapper-arduino for both 1.8.12 and 1.8.13 with the precompiled library so that sounds strange. Anyways, even if the new solution is more hacky than the old one, they're both pretty hacky and the new solution adheres more to the Arduino library standard so I argue that we should go with this one.

**Comment by edumeneses** [comment]
Definitely! 

I've already tested the new commits, and they work as intended (fixing this issue and presenting me with the errors already discussed in Issue #3). I edited my *inet.h* file, and it compiles ok. I'll check later on the GuitarAMI firmware. 

A lot of cool stuff that is already working there will migrate to the T-Stick in the future, including a brand new web server, BLE midi support, and OTA updates.
